name: Check

on:
  pull_request:

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    uses: playframework/.github/.github/workflows/cmd.yml@v2
    with:
      java: 11, 8
      scala: 2.12.15, 2.13.8
      cmd: sbt ++$MATRIX_SCALA "test ; publishLocal ; scripted"

  finish:
    name: Finish
    needs: # Should be last
      - "tests"
    uses: playframework/.github/.github/workflows/rtm.yml@v2
